የባዕድ ሐገር ስሞች ትክክለኛ የግዕዝ ትርጓሜያቸው 

፩. ኮሌጅ ------ መካነ ትምህርት
፪. ዩኒቨርስቲ ------ መካነ አምሮ
፫. ሌክቸር ------ ትምህርተ ጉባኤ
፬. ሌክተቸረር ------ መምህረ ጉባኤ
፭. ዲን ----- ሊቀ ጉባኤ
፯. ቢሮ ------ መስሪያ ቤት
፰. ባንክ ------ ቤተ ንዋይ
፱. ሲቪል ሰርቪስ ------ ሰላማዊ አገልግሎት
፲. Custom ------ ኬላ
፲፩. ኮምፒተር ------ መቀመሪያ
፲፪. ድግሪ ------ ማዕረግ
፲፫. ሚኒስተር ------ ምሉክ
፲፬. Mass media ------ ምህዋረ ዜና
፲፭. ፎቶ ግራፍ ------ ብራናዊ ስዕል
፲፮. ራዲዮ ------ ንፈሰ ድምፅ
፲፯. ፖሊስ ------ የህግ ዘበኛ
፲፰. ኢንተርኔት ------ የህዋ አውታር
፲፱. ሎሬት ------ አምበል ፣ ተሸላሚ የቅኔ
፳. ዶክተር ------ ሊቀ ሙህር
፳፩. ኢምባሲ ------ የእንደራሲ ፅ/ቤት
፳፪. ዲፕሎማት ------ የመንግስት መልክተኞች
፳፫. ኢኮኖሚክስ ------ ስነ ብዕል
፳፬. ሀዋላ ------ ምህዋረ ንዋይ
፳፭. ሳሎን ------ እንግዳ መቀበያ
፳፮. ቱሪዝም ------ ስነ ህዋፄ
፳፯. ስካን ------ ምክታብ
፳፰. ፕሬዝዳንት ------ ሊቀ ሀገር / ሙሴ
፳፱. ቴሌኮሚኒኬሽን ------ ምህዋረ ቃል
፴. ቪዛ ------ የይለፍ ፍቃድ
፴፩. ፓስፖርት ------ የኬላ ማለፊያ
፴፪. ቴሌቪዥን ------ ምስለ መስኮት / መቅረፀ ትይንት
፴፫. Voice Recorder ----መቅረፀ ድምፅ
